### PR TITLE
Fixed numbers, minor word changes

### PR DESCRIPTION
**Pull request by terrorist96**

### CODE REVIEW

**Comment by terrorist96** [comment]
Erase is a narrow word. If I throw away evidence, would it be considered erasing?
I guess a better word would be `taint`. How can I update my pull request?

**Comment by Jean-LouisMesic** [comment]
Eradicate is also a weak word.

Tamper, destroy, etc. are more legally orthodox in this case.

**Comment by terrorist96** [comment]
Yeah, that's good

**Comment by terrorist96** [comment]
This law conflicts with §III.4 of the constitution:

**Comment by terrorist96** [comment]
Looking at it again, it isn't in conflict. The constitution says a maximum of 24 hours while the law stipulates 12 hours.

**Comment by Jean-LouisMesic** [comment]
These laws are only for the time being, anyway. They are in place to solve any issues that arise between citizens and/or the provisional government while we write the constitution and first actual constitutional laws.

**Pull request merged**
